pub mod asset_service;
pub mod catalog;
pub mod collection;
pub mod config;
pub mod contact_sheet;
pub mod content_store;
pub mod device_registry;
pub mod embedded_xmp;
pub mod exif_reader;
pub mod format;
pub mod metadata_store;
pub mod models;
pub mod preview;
pub mod query;
pub mod saved_search;
pub mod shell;
pub mod stack;
pub mod tag_util;
pub mod vlm;
pub mod web;
pub mod xmp_reader;

#[cfg(feature = "ai")]
pub mod ai;
#[cfg(feature = "ai")]
pub mod embedding_store;
#[cfg(feature = "ai")]
pub mod face;
#[cfg(feature = "ai")]
pub mod face_store;
#[cfg(feature = "ai")]
pub mod model_manager;
